# This is just a template file, and it is not used by the app.
# In order for the app to use it:
#
# 1. Rename this file to credentials.toml, which will be ignored by Git.
# 2. Replace the dummy values below with the actual address and key.
#
# IMPORTANT:
# Never use your account's private key.
# Instead, always generate a corresponding API key from Hyperliquid UI.

address = '0x1111111111111111111111111111111111111111'
key = '0x2222222222222222222222222222222222222222222222222222222222222222'
